### ISSUE TITLE
Hive-IO-Components

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#125]
Work on IO classes and components

![image](https://user-images.githubusercontent.com/21927657/72077932-69692c80-32f8-11ea-9c81-4986f548c32d.png)

 Hive-Input components: Grasshopper components, that open a new windows form when you double click on them. Then, using that form, you can specify details, like PV technology (using drop down?), or building construction, etc

- [x] Hive.Input Solar technologies (outside Mothercell). Issue: https://github.com/architecture-building-systems/hive/issues/142
- [x] Hive.Input Building (outside Mothercell). Issue: https://github.com/architecture-building-systems/hive/issues/126
- [x] Hive.Input Environment (outside Mothercell). Issue: https://github.com/architecture-building-systems/hive/issues/145
- [x] Hive.IO.Distributor (inside Mothercell). Issue: https://github.com/architecture-building-systems/hive/issues/143
- [x] Hive.IO.Results (inside Mothercell). Issue: https://github.com/architecture-building-systems/hive/issues/144
- [x] Hive.Results viewer (outside Mothercell). Issue: https://github.com/architecture-building-systems/hive/issues/127

**Comment by christophwaibel** [comment]
Hive-Input components: Grasshopper components, that open a new windows form when you double click on them. Then, using that form, you can specify details, like PV technology (using drop down?), or building construction, etc

**Comment by christophwaibel** [comment]
- [ ] Hive.Input components (outside Mothercell)
- [ ] Hive.IO.Distributor (inside Mothercell)
- [ ] Hive.IO.Results (inside Mothercell)
- [ ] Hive.Results viewer (outside Mothercell, @daren-thomas 's job, issue: )

![image](https://user-images.githubusercontent.com/21927657/73759132-c62afc00-476b-11ea-9eec-fdda4b851c8c.png)

**Comment by christophwaibel** [comment]
prototypes for each existing
