### ISSUE TITLE
Hive01-Example-File-Clustered

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#148]
`Hive01_Example.gh` file that includes all the basics of Hive

- [x] Input Forms (Hive.IO)
- [x] Hive.IO.Distributor
- [x] (manually) clustered Mothercell with Hive/Core simulation models for: (i) demand (SIA380), (ii) solar potentials, (iii) energy supply, (iv) cost and emissions calculator
- [x] Hive.IO.Results
- [x] Hive Results Visualization

- [x] 3D Rhino model Template (on the server: ...\26_HIVE\06_Development\0_Input_Geometry) (https://github.com/architecture-building-systems/hive/issues/47)
